job_change_data = {
	['ambu'] = {name='Ambuscade', char1 = 'blu/rdm', char2 = 'pld/run', char3 = 'rdm/sch', char4 = 'brd/dnc', char5 = 'war/sam', char6 = 'cor/nin',},
	['ody'] = {name='Odyssey Farm', char1 = 'run/pld', char2 = 'sam/war', char3 = 'cor/nin', char4 = 'brd/rdm', char5 = 'whm/sch', char6 = 'sam/war',},
	['alex'] = {name='Alexander', char1 = 'pld/run', char2 = 'thf/war', char3 = 'war/drg', char4 = 'brd/nin', char5 = 'geo/rdm', char6 = 'whm/sch',},
	['sortie'] = {name='Sortie Melee', char1 = 'run/drk', char2 = 'cor/nin', char3 = 'blu/drg', char4 = 'brd/dnc', char5 = 'war/drg', char6 = 'whm/sch',},
	['sortie2'] = {name='Sortie Mage', char1 = 'run/pld', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'sch/whm', char5 = 'geo/rdm', char6 = 'cor/whm',},
	['shinryu'] = {name='Shinryu', char1 = 'thf/war', char2 = 'mnk/war', char3 = 'sch/whm', char4 = 'brd/dnc', char5 = 'whm/sch', char6 = 'geo/rdm',},
	['shinryu2'] = {name='Shinryu Alternative', char1 = 'whm/sch', char2 = 'thf/war', char3 = 'geo/rdm', char4 = 'sch/whm', char5 = 'brd/dnc', char6 = 'mnk/war',},
	['ouryu'] = {name='Ouryu', char1 = 'run/drk', char2 = 'sam/war', char3 = 'cor/dnc', char4 = 'brd/whm', char5 = 'whm/sch', char6 = 'geo/rdm',},
	['cait'] = {name='Cait Sith', char1 = 'run/drk', char2 = 'thf/war', char3 = 'cor/nin', char4 = 'brd/dnc', char5 = 'whm/sch', char6 = 'smn/whm',},
	['dyna'] = {name='Dnyamis W3', char1 = 'pld/blu', char2 = 'sam/drg', char3 = 'cor/nin', char4 = 'brd/dnc', char5 = 'rdm/sch', char6 = 'geo/sch',},
	['dyna2'] = {name='Dnyamis W3 - Alternative', char1 = 'pld/blu', char2 = 'cor/nin', char3 = 'rdm/sch', char4 = 'brd/dnc', char5 = 'geo/sch', char6 = 'sam/drg',},
	['mboze1'] = {name='Mboze Farm #1', char1 = 'blu/rdm', char2 = 'mnk/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'run/rdm', char6 = 'whm/rdm',},
	['mboze2'] = {name='Mboze Farm #2', char1 = 'pld/rdm', char2 = 'sam/rdm', char3 = 'rdm/thf', char4 = 'cor/rdm', char5 = 'bst/rdm', char6 = 'pup/rdm',},
	['mboze3'] = {name='Mboze Farm #3', char1 = 'thf/rdm', char2 = 'nin/rdm', char3 = 'drk/rdm', char4 = 'sch/rdm', char5 = 'geo/rdm', char6 = 'smn/rdm',},
	['ongo1'] = {name='Ongo Farm #1', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'blu/rdm', char4 = 'war/rdm', char5 = 'rdm/thf', char6 = 'nin/rdm',},
	['ongo2'] = {name='Ongo Farm #2', char1 = 'pld/rdm', char2 = 'cor/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/rdm', char6 = 'smn/rdm',},
	['ongo3'] = {name='Ongo Farm #3', char1 = 'thf/rdm', char2 = 'pup/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'bst/rdm', char6 = 'mnk/rdm',},
	['bumbapre'] = {name='Bumba Pre-fight', char1 = 'run/rdm', char2 = 'bst/rdm', char3 = 'sch/rdm', char4 = 'blm/rdm', char5 = 'rdm/thf', char6 = 'smn/rdm',},
	['bumba'] = {name='Bumba Main', char1 = 'war/rdm', char2 = 'cor/rdm', char3 = 'drg/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'geo/rdm',},
	['bumba1'] = {name='Bumba Farm #1', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'rng/rdm', char4 = 'cor/rdm', char5 = 'rdm/thf', char6 = 'thf/rdm',},
	['bumba2'] = {name='Bumba Farm #2', char1 = 'run/rdm', char2 = 'nin/rdm', char3 = 'sch/rdm', char4 = 'blm/rdm', char5 = 'dnc/thf', char6 = 'smn/rdm',},
	['bumba3'] = {name='Bumba Farm #3', char1 = 'blu/rdm', char2 = 'mnk/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'pup/rdm',},
	['arebatipre'] = {name='Arebati Pre-fight', char1 = 'run/rdm', char2 = 'sam/rdm', char3 = 'geo/rdm', char4 = 'smn/rdm', char5 = 'whm/thf', char6 = 'mnk/rdm',},
	['arebatiwar'] = {name='Arebati Main - Melee', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/thf', char6 = 'cor/rdm',},
	['arebatirng'] = {name='Arebati Main - Ranged', char1 = 'run/rdm', char2 = 'rng/rdm', char3 = 'sch/rdm', char4 = 'brd/rdm', char5 = 'geo/thf', char6 = 'cor/rdm',},
	['kalunga'] = {name='Kalunga Main', char1 = 'run/rdm', char2 = 'cor/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'geo/rdm',},
	['kalunga1'] = {name='Kalunga Farm #1', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'drk/rdm', char4 = 'sch/rdm', char5 = 'brd/rdm', char6 = 'mnk/rdm',},
	['kalunga2'] = {name='Kalunga Farm #2', char1 = 'run/rdm', char2 = 'sam/rdm', char3 = 'blu/rdm', char4 = 'geo/rdm', char5 = 'rdm/thf', char6 = 'thf/rdm',},
	['kalunga3'] = {name='Kalunga Farm #3', char1 = 'war/rdm', char2 = 'pup/rdm', char3 = 'cor/rdm', char4 = 'blm/rdm', char5 = 'whm/rdm', char6 = 'nin/rdm',},
	['marm'] = {name='Marmorkrebs Clear', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['procne'] = {name='Procne Clear', char1 = 'war/rdm', char2 = 'pld/rdm', char3 = 'drg/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
}

stage_data = {
	['ambu'] = { jobs = {
		['RDM'] = {	'hb moblist add \"Bozzetto Pishogue\"; hb moblist on; hb aoe on; hb mincure 4; mc buffall haste2; hb buffjob tank refresh3; hb buffjob BLU refresh3; dfull; hb ind on;'},
		['BLU'] = {	'azuresets set mboze; gs c set weapons macc; gs c set autobluspam on; hb buff me aquaveil'},
		['BRD'] = { 'wait 2.5; sing pl meleehaste2; sing ballad 1 tank; gs c set weapons DualSavage; sing ballad 2 BLU; hb as attack on; hb as j WAR; hb f j WAR; sing ballad 1 RDM'},
		['PLD'] = {	'lua r react',},
		['WAR'] = {	'gs c set weapons Loxotic; hb f off'},
		['COR'] = {	'gs c set weapons DualSavage; roll melee; hb as attack on; hb as j WAR; hb f j WAR'},
		['ALL'] = {	commands = 'input /autotarget off; gs c othertargetws Bozzetto Pishogue; gs c set AutoOtherTargetWS on;', mc_settings = {autows=true}},
	}},
	['gige'] = { jobs = {
		['RDM'] = {	'hb f dist 6; hb f j WAR; hb as nolock; hb as j WAR; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Gigelorum\'s Matamata\";',
					'hb debuff slow2,paralyze2,addle2,gravity2,dia3,inundation; hb buffjob tank refresh3; hb buffjob MNK refresh3; hb buffjob WAR refresh3; hb mincure 4; mc buffall haste2;'},
		['RUN'] = {	'hb buff me shell5; hb as off; hb f off;'},
		['BRD'] = { 'wait 2.5; sing pl gige; sing n on; sing p on; sing sirvente tank; sing ballad 1 tank; sing ballad 2 RDM; gs c set weapons Carnwenhan'},
		['MNK'] = {	'gs c set weaponskillmode Enmity',},
		['WAR'] = {	'lua l dressup; gs c set weapons Loxotic; gs c set weaponskillmode Enmity; hb f dist 12; hb f j TANK'},
		['COR'] = {	'gs c set weapons Naegling; roll melee;'},
		['ALL'] = {	commands = '', mc_settings = {autows=true}},
	}},
	['aris'] = { jobs = {
		['WHM'] = {	'hb buff me auspice,aquaveil,barfira,baramnesra; gs c set castingmode SIRD; mc buffall haste; hb debuff dia2; hb as j WAR; hb as nolock; hb disable erase',},
		['GEO'] = {	'gs c autogeo fury; gs c autoindi barrier; gs c autoentrust STR'},
		['BRD'] = { 'wait 2.5; sing pl aris; sing n on; sing p on; sing ballad 2 whm; gs c set weapons Carnwenhan; sing debuff carnage elegy; sing aoe off; sing d on;'},
		['SAM'] = {	'gs c set weaponskillmode Enmity; gs c set defensedownmode on;',},
		['WAR'] = {	'lua l dressup; gs c set weapons Naegling; gs c set autotomahawkmode on;'},
		['COR'] = {	'gs c set weapons Naegling; roll melee;'},
		['ALL'] = {	commands = 'autoitem off', mc_settings = {autows=true}},
	}},
	['procne'] = { jobs = {
		['RDM'] = {	'hb f dist 6; hb f j WAR; hb as nolock; hb as j WAR; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Procne\'s Tulfaire\"; hb buffjob tank shell5;',
					'hb debuff slow2,paralyze2,addle2,gravity2,dia3,inundation; hb buffjob tank refresh3; hb buffjob WAR refresh3; hb mincure 4; mc buffall haste2;'},
		['PLD'] = {	'hb as off; hb f off;'},
		['BRD'] = { 'wait 2.5; sing pl procne; sing n on; sing p on; sing ballad 1 tank; sing wind 1 tank; sing sirvente tank; sing ballad 2 RDM; gs c set weapons Carnwenhan'},
		['DRG'] = {	'gs c set weapons Trishula;',},
		['WAR'] = {	'lua l dressup; gs c set weapons ShiningOne; gs c set weaponskillmode Enmity;'},
		['COR'] = {	'gs c set weapons Fomalhaut; roll melee;'},
		['ALL'] = {	commands = '', mc_settings = {autows=true}},
	}},
	['henwen'] = { jobs = {
		['RDM'] = {	'hb f dist 6; hb f j WAR; hb as nolock; hb as j WAR; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Henwen\'s Raaz\";',
					'hb debuff slow2,paralyze2,addle2,gravity2,dia3,inundation; hb buffjob tank refresh3; hb buffjob MNK refresh3; hb buffjob WAR refresh3; hb mincure 4; mc buffall haste2;'},
		['PLD'] = {	'hb buff me shell5; hb as off; hb f off;'},
		['BRD'] = { 'wait 2.5; sing pl gige; sing n on; sing p on; sing sirvente tank; sing ballad 1 tank; sing ballad 2 RDM; gs c set weapons Carnwenhan'},
		['MNK'] = {	'gs c set weaponskillmode Enmity',},
		['WAR'] = {	'lua l dressup; gs c set weapons Loxotic; gs c set weaponskillmode Enmity; hb f dist 12; hb f j TANK; hb as j MNK; gs c set autotomahawkmode on;'},
		['COR'] = {	'gs c set weapons Naegling; roll melee;'},
		['ALL'] = {	commands = '', mc_settings = {autows=true}},
	}},
	['marm'] = { jobs = {
		['BLM'] = {	'gs c set MagicBurstMode lock; gs c set elementalmode lightning;'},
		['SCH'] = {	'gs c set MagicBurstMode lock; gs c set elementalmode lightning; schnuke; gs c set autosubmode off;'},
		['GEO'] = {	'gs c set MagicBurstMode lock; gs c set elementalmode lightning; iacumen; gmalaise; gs c autoentrust INT'},
		['COR'] = { 'gs c set weapons fomalhaut; roll roll1 evokers; roll roll2 wizards;'},
		['RDM'] = {	'hb buffjob BLM refresh3,haste2; hb buffjob SCH refresh3,haste2; hb buffjob GEO refresh3,haste2; hb buffjob tank refresh3,haste2,shell5,protect5; hb buffjob COR flurry2;',
					'hb debuff slow2,paralyze2,gravity2,bio3,inundation; hb as nolock on; hb as j tank; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Marmorkrebs\'s Cracklaw\";'},
		['RUN'] = {	'gs c set hybridmode MEVA; gs c set RuneElement Sulpor; gs c set autotankmode on; hb buff me barwater; hb f off'},
		['ALL'] = {	commands = 'hb f dist 2.7; autoitem on;', mc_settings = {autows=false,autosc=true,autosub='off'}},
	}},
	['rask'] = { jobs = {
		['BLM'] = {	'gs c set MagicBurstMode lock; gs c set elementalmode wind;'},
		['SCH'] = {	'gs c set MagicBurstMode lock; gs c set elementalmode wind; schnuke; gs c set autosubmode off;'},
		['GEO'] = {	'gs c set MagicBurstMode lock; gs c set elementalmode wind; iacumen; gmalaise; gs c autoentrust INT'},
		['COR'] = { 'gs c set weapons fomalhaut; roll roll1 evokers; roll roll2 wizards;'},
		['RDM'] = {	'hb buffjob BLM refresh3,haste2; hb buffjob SCH refresh3,haste2; hb buffjob GEO refresh3,haste2; hb buffjob tank refresh3,haste2,shell5,protect5; hb buffjob COR flurry2;',
					'hb debuff slow2,paralyze2,gravity2,bio3,inundation; hb as nolock on; hb as j tank; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Raskovniche\'s Snapweed\";'},
		['RUN'] = {	'gs c set hybridmode MEVA; gs c set RuneElement Flabra; gs c set autotankmode on; hb buff me barstone; hb f off'},
		['ALL'] = {	commands = 'hb f dist 2.7; autoitem on;', mc_settings = {autows=false,autosc=true,autosub='off'}},
	}},
	['wave1'] = { jobs = {
		['RDM'] = {	'mc buffall haste2; wait 1.0; mc buffall shell5; wait 1.0; hb buff me enthunder; hb buffjob tank refresh3,protect5,shell5; hb aoe on;',
					'hb mincure 4; hb buffjob GEO refresh3; dmain; hb buffjob SAM refresh3;'},
		['PLD'] = {	'hb buff me shell5; hb as off; hb f off;'},
		['BRD'] = { 'wait 1; gs c set treasuremode tag; hb minwaltz 3; gs c weapons DualCarn; sing pl melee; sing n off; sing p on; sing d on; hb debuff wind threnody II; sing debuff carnage elegy;',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM;',
					'wait 1.5; sing sirvente tank; sing ballad 1 tank',
					'wait 1.5; sing ballad 1 WHM; sing ballad 2 SCH'},
		['SAM'] = {	'gs c set hybridmode normal; gs c set weapons Masamune; gs c set DefenseDownMode tag'},
		['GEO'] = {	'gs c set castingmode DT; gs c set idlemode DT; gmalaise; iacumen; hb mincure 4; hb aoe on',
					'wait 0.7; hb buffjob SAM windstorm; hb buffjob RDM aurorastorm; hb buffjob BRD aurorastorm; hb buffjob tank aurorastorm;'},
		['COR'] = {	'gs c autows leaden salute; gs c set weapons DualLeadenRanged; roll roll1 tact; roll roll2 wizard;'},
		['ALL'] = {	commands = 'input /autotarget off', mc_settings = {autows=true,autosub='off'}},
	}},
	['wave2'] = { jobs = {
		['RDM'] = {	'mc buffall haste2; wait 1.0; mc buffall shell5; wait 1.0; hb buff me enthunder; hb buffjob tank refresh3,protect5,shell5; hb mincure 4; hb aoe on;',
					'hb buffjob GEO refresh3; dfull; gs c autows savage blade; hb buffjob SAM refresh3; gs c set weapons Naegling;'},
		['PLD'] = {	'hb buff me shell5; hb as off; hb f off;'},
		['BRD'] = { 'wait 1; gs c set treasuremode tag; hb minwaltz 3; gs c weapons DualCarn; sing pl w2; sing n off; sing p on; sing d on; hb debuff wind threnody II; sing debuff carnage elegy; gs c set autozergmode on;',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM;',
					'wait 1.5; sing sirvente tank; sing ballad 1 tank',
					'wait 1.5; sing ballad 1 WHM; sing ballad 2 SCH'},
		['SAM'] = {	'gs c set hybridmode DT; gs c set weapons Masamune; gs c set DefenseDownMode tag; gs c set weaponskillmode Enmity;'},
		['GEO'] = {	'gs c set castingmode DT; gs c set idlemode DT; gfury; ibarrier; gs c autoentrust frailty; hb mincure 4; hb aoe on',
					'wait 0.7; hb buffjob SAM windstorm; hb buffjob RDM aurorastorm; hb buffjob BRD aurorastorm; hb buffjob tank aurorastorm;'},
		['COR'] = {	'gs c set weapons DualSavage; gs c autows savage blade; roll melee;'},
		['ALL'] = {	commands = 'input /autotarget off', mc_settings = {autows=true,autosub='off'}},
	}},
	['shinryu'] = { jobs = {
		['WHM'] = {	'hb buff me barfira; hb buff me barparalyzra; hb buff me aquaveil; hb buff me auspice; hb buffjob MNK haste; hb debuff dia2; hb buffjob BRD haste;'},
		['SCH'] = {	'gs c set elementalmode light; hb debuff dia2; hb buff me regen5; hb buff me aquaveil; hb buffjob BRD aurorastorm2; hb buffjob WHM aurorastorm2; hb buffjob THF haste;',
					'hb buffjob COR haste; schheal;'},
		['BRD'] = { 'wait 2.5; sing pl shin; sing n on; sing p on; gs c set weapons DualCarn; sing ballad 1 WHM; sing ballad 2 SCH; sing ballad 2 GEO; lua r react;'},
		['MNK'] = {	'gs c set hybridmode DT',},
		['THF'] = {	'gs c set treasuremode fulltime;'},
		['GEO'] = {	'irefresh; gfury; gs c autoentrust frailty; hb debuff dia2;'},
		['ALL'] = {	commands = 'lua r gazecheck; wait 3; gaze ag off; wait 1; gaze ap on;', mc_settings = {autows=true}},
	}},

	
}

return job_data
       