wsall_data = {
	['WAR'] = 'Upheaval',
	['MNK'] = 'Victory Smite',
	['WHM'] = 'Black Halo',
	['BLM'] = 'Vidohunir',
	['RDM'] = 'Savage Blade',
	['THF'] = 'Rudra\'s Storm',
	['PLD'] = 'Atonement',
	['DRK'] = 'Torcleaver',
	['BST'] = 'Decimation',
	['BRD'] = 'Rudra\'s Storm',
	['RNG'] = 'Last Stand',
	['SAM'] = 'Tachi: Fudo',
	['NIN'] = 'Blade: Chi',
	['DRG'] = 'Stardiver',
	['SMN'] = 'Garland of Bliss',
	['BLU'] = 'Expiacion',
	['COR'] = 'Last Stand',
	['PUP'] = 'Victory Smite',
	['DNC'] = 'Pyrrhic Kleos',
	['SCH'] = 'Omniscience',
	['GEO'] = 'Black Halo',
	['RUN'] = 'Dimidiation',
}

wstype_data = {
	['WAR'] = {wsgroup={}},
	['MNK'] = {wsgroup={}},
	['WHM'] = {wsgroup={}},
	['BLM'] = {wsgroup={}},
	['RDM'] = {wsgroup={}},
	['THF'] = {wsgroup={}},
	['PLD'] = {wsgroup={}},
	['DRK'] = {wsgroup={}},
	['BST'] = {wsgroup={}},
	['BRD'] = {wsgroup={}},
	['RNG'] = {wsgroup={}},
	['SAM'] = {wsgroup={
		['fudo'] = {
			['NON']='gs c set weapons Masamune; gs c autows Tachi: Fudo',
		},
		['jinpu'] = {
			['NON']='gs c set weapons Dojikiri; gs c autows Tachi: Jinpu',
		},
		['goten'] = {
			['NON']='gs c set weapons Dojikiri; gs c autows Tachi: Goten',
		},
		['kagero'] = {
			['NON']='gs c set weapons Dojikiri; gs c autows Tachi: Kagero',
		},
		['koki'] = {
			['NON']='gs c set weapons Dojikiri; gs c autows Tachi: Koki',
		},
		['slash'] = {
			['NON']='gs c set weapons Masamune; gs c autows Tachi: Fudo',
		},
		['hybrid'] = {
			['NON']='gs c set weapons Dojikiri; gs c autows Tachi: Jinpu',
		},
		['hybridvolte'] = {
			['NON']='gs c set weapons Dojikiri; gs c autows Tachi: Jinpu',
		},
	}},
	['NIN'] = {wsgroup={}},
	['DRG'] = {wsgroup={}},
	['SMN'] = {wsgroup={}},
	['BLU'] = {wsgroup={}},
	['COR'] = {wsgroup={
		['leaden'] = {
			['NIN']='gs c set weapons DualLeaden; gs c autows Leaden Salute',
			['DNC']='gs c set weapons DualLeaden; gs c autows Leaden Salute',
			['NON']='gs c set weapons DeathPenalty; gs c autows Leaden Salute',
		},
		['savage'] = {
			['NIN']='gs c set weapons DualSavage; gs c autows Savage Blade',
			['DNC']='gs c set weapons DualSavage; gs c autows Savage Blade',
			['NON']='gs c set weapons Naegling; gs c autows Savage Blade',
		},
		['wildfire'] = {
			['NIN']='gs c set weapons DualWildfire; gs c autows Wildfire',
			['DNC']='gs c set weapons DualWildfire; gs c autows Wildfire',
			['NON']='gs c set weapons Armageddon; gs c autows Wildfire',
		},
		['slash'] = {
			['NIN']='gs c set weapons DualSavage; gs c autows Savage Blade',
			['DNC']='gs c set weapons DualSavage; gs c autows Savage Blade',
			['NON']='gs c set weapons Naegling; gs c autows Savage Blade',
		},
		['pierce'] = {
			['NIN']='gs c set weapons DualLastStand; gs c autows Last Stand',
			['DNC']='gs c set weapons DualLastStand; gs c autows Last Stand',
			['NON']='gs c set weapons Fomalhaut; gs c autows Last Stand',
		},
		['blunt'] = {
			['NIN']='gs c set weapons DualWildfire; gs c autows Wildfire',
			['DNC']='gs c set weapons DualWildfire; gs c autows Wildfire',
			['NON']='gs c set weapons Armageddon; gs c autows Wildfire',
		},
		['magic'] = {
			['NIN']='gs c set weapons DualLeaden; gs c autows Leaden Salute',
			['DNC']='gs c set weapons DualLeaden; gs c autows Leaden Salute',
			['NON']='gs c set weapons DeathPenalty; gs c autows Leaden Salute',
		},
		['hybrid'] = {
			['NIN']='gs c set weapons DualLeaden; gs c autows Leaden Salute',
			['DNC']='gs c set weapons DualLeaden; gs c autows Leaden Salute',
			['NON']='gs c set weapons DeathPenalty; gs c autows Leaden Salute',
		},
		['hybridvolte'] = {
			['NIN']='gs c set weapons DualWildfire; gs c autows Wildfire',
			['DNC']='gs c set weapons DualWildfire; gs c autows Wildfire',
			['NON']='gs c set weapons Armageddon; gs c autows Wildfire',
		},
	}},
	['PUP'] = {wsgroup={}},
	['DNC'] = {wsgroup={}},
	['SCH'] = {wsgroup={}},
	['GEO'] = {wsgroup={}},
	['RUN'] = {wsgroup={}},
}

crowd_control_data = {
	['WHM'] = {
		['BLM'] = {spell='Sleepga II'},
		['RDM'] = {spell='Sleep II'}},
	['BLM'] = {
		['NON'] = {spell='Sleepga II'}},
	['RDM'] = {
		['BLM'] = {spell='Sleepga II'},
		['NON'] = {spell='Sleep II'}},
	['BRD'] = {
		['NON'] = {spell='Horde Lullaby II'}},
	['SCH'] = {
		['BLM'] = {spell='Sleepga II'},
		['RDM'] = {spell='Sleep II'}},
	['GEO'] = {
		['BLM'] = {spell='Sleepga II'},
		['RDM'] = {spell='Sleep II'}},
}

job_change_data = {
	['ambu'] = {name='Ambuscade', char1 = 'blu/rdm', char2 = 'pld/run', char3 = 'rdm/sch', char4 = 'brd/dnc', char5 = 'war/sam', char6 = 'cor/nin',},
	['ody'] = {name='Odyssey Farm', char1 = 'run/pld', char2 = 'sam/war', char3 = 'cor/nin', char4 = 'brd/rdm', char5 = 'whm/sch', char6 = 'sam/war',},
	['alex'] = {name='Alexander', char1 = 'pld/run', char2 = 'thf/war', char3 = 'war/drg', char4 = 'brd/nin', char5 = 'geo/rdm', char6 = 'whm/sch',},
	['sortie'] = {name='Sortie Melee', char1 = 'run/drk', char2 = 'cor/nin', char3 = 'blu/drg', char4 = 'brd/dnc', char5 = 'war/drg', char6 = 'whm/sch',},
	['sortie2'] = {name='Sortie Mage', char1 = 'run/pld', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'sch/whm', char5 = 'geo/rdm', char6 = 'cor/whm',},
	['shinryu'] = {name='Shinryu', char1 = 'thf/war', char2 = 'mnk/war', char3 = 'sch/whm', char4 = 'brd/dnc', char5 = 'whm/sch', char6 = 'geo/rdm',},
	['shinryu2'] = {name='Shinryu Alternative', char1 = 'whm/sch', char2 = 'thf/war', char3 = 'geo/rdm', char4 = 'sch/whm', char5 = 'brd/dnc', char6 = 'mnk/war',},
	['ouryu'] = {name='Ouryu', char1 = 'run/drk', char2 = 'sam/war', char3 = 'cor/dnc', char4 = 'brd/whm', char5 = 'whm/sch', char6 = 'geo/rdm',},
	['cait'] = {name='Cait Sith', char1 = 'run/drk', char2 = 'thf/war', char3 = 'cor/nin', char4 = 'brd/dnc', char5 = 'whm/sch', char6 = 'smn/whm',},
	['dyna'] = {name='Dnyamis W3', char1 = 'pld/blu', char2 = 'sam/drg', char3 = 'cor/nin', char4 = 'brd/dnc', char5 = 'rdm/sch', char6 = 'geo/sch',},
	['dyna2'] = {name='Dnyamis W3 - Alternative', char1 = 'pld/blu', char2 = 'cor/nin', char3 = 'rdm/sch', char4 = 'brd/dnc', char5 = 'geo/sch', char6 = 'sam/drg',},
	['mboze1'] = {name='Mboze Farm #1', char1 = 'blu/rdm', char2 = 'mnk/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'run/rdm', char6 = 'whm/rdm',},
	['mboze2'] = {name='Mboze Farm #2', char1 = 'pld/rdm', char2 = 'sam/rdm', char3 = 'rdm/thf', char4 = 'cor/rdm', char5 = 'bst/rdm', char6 = 'pup/rdm',},
	['mboze3'] = {name='Mboze Farm #3', char1 = 'thf/rdm', char2 = 'nin/rdm', char3 = 'drk/rdm', char4 = 'sch/rdm', char5 = 'geo/rdm', char6 = 'smn/rdm',},
	['ongo1'] = {name='Ongo Farm #1', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'blu/rdm', char4 = 'war/rdm', char5 = 'rdm/thf', char6 = 'nin/rdm',},
	['ongo2'] = {name='Ongo Farm #2', char1 = 'pld/rdm', char2 = 'cor/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/rdm', char6 = 'smn/rdm',},
	['ongo3'] = {name='Ongo Farm #3', char1 = 'thf/rdm', char2 = 'pup/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'bst/rdm', char6 = 'mnk/rdm',},
	['bumbapre'] = {name='Bumba Pre-fight', char1 = 'run/rdm', char2 = 'bst/rdm', char3 = 'sch/rdm', char4 = 'blm/rdm', char5 = 'rdm/thf', char6 = 'smn/rdm',},
	['bumba'] = {name='Bumba Main', char1 = 'war/rdm', char2 = 'cor/rdm', char3 = 'drg/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'geo/rdm',},
	['bumba1'] = {name='Bumba Farm #1', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'rng/rdm', char4 = 'cor/rdm', char5 = 'rdm/thf', char6 = 'thf/rdm',},
	['bumba2'] = {name='Bumba Farm #2', char1 = 'run/rdm', char2 = 'nin/rdm', char3 = 'sch/rdm', char4 = 'blm/rdm', char5 = 'dnc/thf', char6 = 'smn/rdm',},
	['bumba3'] = {name='Bumba Farm #3', char1 = 'blu/rdm', char2 = 'mnk/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'pup/rdm',},
	['arebatipre'] = {name='Arebati Pre-fight', char1 = 'run/rdm', char2 = 'sam/rdm', char3 = 'geo/rdm', char4 = 'smn/rdm', char5 = 'whm/thf', char6 = 'mnk/rdm',},
	['arebatiwar'] = {name='Arebati Main - Melee', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/thf', char6 = 'cor/rdm',},
	['arebatirng'] = {name='Arebati Main - Ranged', char1 = 'run/rdm', char2 = 'rng/rdm', char3 = 'sch/rdm', char4 = 'brd/rdm', char5 = 'geo/thf', char6 = 'cor/rdm',},
	['kalunga'] = {name='Kalunga Main', char1 = 'run/rdm', char2 = 'cor/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'geo/rdm',},
	['kalungav25'] = {name='Kalunga V25', char1 = 'blu/rdm', char2 = 'pld/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'run/thf', char6 = 'cor/rdm',},
	['gog1'] = {name='Gogmagog Farm #1', char1 = 'pld/rdm', char2 = 'smn/rdm', char3 = 'blu/rdm', char4 = 'sch/rdm', char5 = 'sam/rdm', char6 = 'mnk/rdm',},
	['kalungafarm'] = {name='Kalunga Farm', char1 = 'run/rdm', char2 = 'bst/rdm', char3 = 'geo/rdm', char4 = 'brd/rdm', char5 = 'war/rdm', char6 = 'whm/rdm',},
	['gog2'] = {name='Gogmagog Farm #2', char1 = 'drg/rdm', char2 = 'thf/rdm', char3 = 'drk/rdm', char4 = 'blm/rdm', char5 = 'rdm/drk', char6 = 'cor/rdm',},
	['daelan'] = {name='Daelan-dhe Clear', char1 = 'pld/rdm', char2 = 'sam/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['ubnai'] = {name='U Bnai Clear', char1 = 'pld/rdm', char2 = 'sam/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['gogmagog'] = {name='Gogmagog Clear', char1 = 'pld/rdm', char2 = 'mnk/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['sgili'] = {name='Sgili Clear', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['aris'] = {name='Aristaeus Clear', char1 = 'war/rdm', char2 = 'sam/rdm', char3 = 'cor/rdm', char4 = 'brd/rdm', char5 = 'whm/rdm', char6 = 'geo/rdm',},
	['marm'] = {name='Marmorkrebs Clear', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['rask'] = {name='Raskovniche Clear', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['procne'] = {name='Procne Clear', char1 = 'war/rdm', char2 = 'pld/rdm', char3 = 'drg/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['henwen'] = {name='Henwen Clear', char1 = 'pld/rdm', char2 = 'mnk/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
	['gige'] = {name='Gigelorum Clear', char1 = 'run/rdm', char2 = 'mnk/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/whm', char6 = 'cor/rdm',},
}

stage_data = {
	['ambu'] = { jobs = {
		['RDM'] = {	action={'hb moblist add \"Bozzetto Pishogue\"; hb moblist on; hb aoe on; hb mincure 4; mc buffall haste2;',
					'hb buffjob tank refresh3; hb buffjob BLU refresh3; dfull; hb ind on;'},},
		['BLU'] = {	action={'azuresets set mboze; gs c set weapons macc; gs c set autobluspam on; hb buff me aquaveil'}},
		['BRD'] = { action={'wait 2.5; sing pl meleehaste2; sing ballad 1 tank; gs c set weapons DualSavage; sing ballad 2 BLU; hb as attack on; hb as j WAR; hb f j WAR; sing ballad 1 RDM'},},
		['PLD'] = {	action={'lua r react',}},
		['WAR'] = {	action={'gs c set weapons Loxotic; hb f off'}},
		['COR'] = {	action={'gs c set weapons DualSavage; roll melee; hb as attack on; hb as j WAR; hb f j WAR'}},
		['ALL'] = {	commands = 'input /autotarget off; gs c othertargetws Bozzetto Pishogue; gs c set AutoOtherTargetWS on;', mc_settings = {autows=true}},
	}},
	['ml'] = { jobs = {
		['WHM'] = {	action={'hb debuff slow,paralyze; hb buff <me> boost-str,auspice,regen4;'}},
		['SCH'] = {	action={'schheal; hb buff <me> regen5;'}},
		['BRD'] = {	action={'wait 1; hb debuff horde lullaby 2; sing pl meleeacc; gs c set weapons DualCarn;,',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM; sing ballad 1 tank; sing ballad 1 WHM; sing ballad 2 SCH;'}},
		['GEO'] = {	action={'hb debuff dia2; gs c autoentrust refresh;'}},
		['COR'] = {	action={'gs c set weapons DualSavage; roll roll1 exp; roll roll2 sam;'}},
		['ALL'] = {	commands = 'ai off; chatter on;', mc_settings = {autows=true}},
	}},
	['exp'] = { jobs = {
		['BRD'] = {	action={'wait 2.5; sing n off; sing pl mage'}},
		['BLU'] = {	action={'gaze ap off; gs c set weapons Magic; azuresets set solo;'}},
		['COR'] = {	action={'roll exp'}},
		['GEO'] = {	action={'irefresh; ghaste'}},
		['ALL'] = {	commands = '', mc_settings = {autows=true}},
	}},
	['kraken'] = { jobs = {
		['PUP'] = {	action={'gs c set petmode melee; gs c set AutoManeuvers melee; gs c set weapons Xiucoatl; autocontrol equipset kraken'}},
		['COR'] = {	action={'roll roll1 beast; roll roll2 drachen'}},
		['ALL'] = {	commands = 'autoitem off', mc_settings = {autows=true}},
	}},
	['ody'] = { jobs = {
		['WHM'] = {	action={'wait 1.5; gaze ap off; hb buffjob SAM haste; hb buffjob tank regen4; hb ignore_debuff all poison'}, food='Maringna'},
		['RUN'] = {	action={'wait 1.5; gaze ap off; gs c set runeelement sulpor; hb mincure 4;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 2.5; sing d off; gaze ap on; gs c set weapons carnwenhan; sing pl melee; sing n off; sing p on; sing ballad 1 WHM; hb buffjob COR haste; hb buffjob RUN haste;'}, food='Grape Daifuku'},
		['SAM'] = {	action={'wait 1.5; gaze ap on;'}, food='Grape Daifuku'},
		['WAR'] = {	action={'wait 1.5; gaze ap on; gs c set weapons Naegling;'}, food='Grape Daifuku'},
		['COR'] = {	action={'wait 1.5; roll melee; gaze ap on; gs c autows Leaden Salute'}, food='Grape Daifuku'},
		['ALL'] = {	commands = 'lua r gazecheck; input /autotarget on', mc_settings = {autows=true}},
	}},
	['wave1'] = { jobs = {
		['RDM'] = {	action={'mc buffall haste2; wait 1.0; mc buffall shell5; wait 1.0; hb buff me enthunder; hb buffjob tank refresh3,protect5,shell5; hb aoe on;',
					'hb mincure 4; hb buffjob GEO refresh3; dmain; hb buffjob SAM refresh3.windstorm;'}},
		['PLD'] = {	action={'hb as off; hb f off;'}},
		['BRD'] = {	action={'wait 1; gs c set treasuremode tag; hb minwaltz 3; gs c weapons DualCarn; sing pl melee; sing n off; sing p on; sing d on; hb debuff wind threnody II; sing debuff carnage elegy;',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM;',
					'wait 1.5; sing sirvente tank; sing ballad 1 tank',}},
		['SAM'] = {	action={'gs c set hybridmode normal; gs c set weapons Masamune; gs c set DefenseDownMode tag'}},
		['GEO'] = {	action={'gmalaise; iacumen; hb mincure 4; hb aoe on',
					'wait 0.7; hb buffjob BRD aurorastorm; hb buffjob tank aurorastorm;'}},
		['COR'] = {	action={'gs c autows leaden salute; gs c set weapons DualLeadenRanged; roll roll1 tact; roll roll2 wizard;'}},
		['ALL'] = {	commands = 'input /autotarget off', mc_settings = {autows=true,autosub='off'}},
	}},
	['wave2'] = { jobs = {
		['RDM'] = {	action={'mc buffall haste2; wait 1.0; mc buffall shell5; wait 1.0; hb buff me enthunder; hb buffjob tank refresh3,protect5,shell5; hb mincure 4; hb aoe on;',
					'hb buffjob GEO refresh3; dfull;  gs c set weapons Naegling; gs c autows savage blade; hb buffjob SAM refresh3,windstorm;'}, food='Rolan. Daifuku'},
		['PLD'] = {	action={'hb as off; hb f off;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 1; gs c set treasuremode tag; hb minwaltz 3; gs c weapons DualCarn; sing pl w2; sing n off; sing p on; sing d on; hb debuff wind threnody II; sing debuff carnage elegy; gs c set autozergmode on;',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM;',
					'wait 1.5; sing sirvente tank; sing ballad 1 tank',}, food='Grape Daifuku'},
		['SAM'] = {	action={'gs c set hybridmode DT; gs c set weapons Masamune; gs c set DefenseDownMode tag; gs c set weaponskillmode Enmity;'}, food='Rolan. Daifuku'},
		['GEO'] = {	action={'gfury; ibarrier; gs c autoentrust frailty; hb mincure 4; hb aoe on',
					'wait 0.7; hb buffjob BRD aurorastorm; hb buffjob tank aurorastorm;'}, food='Grape Daifuku'},
		['COR'] = {	action={'gs c set weapons DualSavage; gs c autows savage blade; roll melee;'}, food='Rolan. Daifuku'},
		['ALL'] = {	commands = 'input /autotarget off', mc_settings = {autows=true,autosub='off'}},
	}},
	['wave3'] = { jobs = {
		['RDM'] = {	action={'mc buffall haste2; wait 1.0; mc buffall shell5; wait 1.0; hb buff me enthunder; hb buffjob tank refresh3,protect5,shell5; hb mincure 4; hb aoe on;',
					'hb buffjob GEO refresh3; dvolte; gs c set weapons Crocea; gs c autows Seraph Blade; hb buffjob SAM refresh3,windstorm;'}, food='Rolan. Daifuku'},
		['PLD'] = {	action={'hb as off; hb f off;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 1; gs c set treasuremode tag; hb minwaltz 3; gs c weapons DualCarn; sing pl w3; sing n off; sing p on; sing d on; hb debuff wind threnody II; sing debuff carnage elegy; gs c set autozergmode off;',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM;',
					'wait 1.5; sing sirvente tank; sing ballad 1 tank',}, food='Grape Daifuku'},
		['SAM'] = {	action={'gs c set hybridmode normal; gs c set weapons Dojikiri; gs c autows Tachi: Jinpu; gs c set DefenseDownMode tag; gs c set weaponskillmode Enmity;'}, food='Rolan. Daifuku'},
		['GEO'] = {	action={'gmalaise; iacumen; gs c autoentrust fury; hb mincure 4; hb aoe on',
					'wait 0.7; hb buffjob BRD aurorastorm; hb buffjob tank aurorastorm;'}, food='Grape Daifuku'},
		['COR'] = {	action={'gs c set weapons DualWildfire; gs c autows Wildfire; roll melee; wait 1; roll roll2 wizard;'}, food='Rolan. Daifuku'},
		['ALL'] = {	commands = 'input /autotarget off; hb unignore_debuff all defense down,slow,addle,inhibit tp,plague,dia,bio', mc_settings = {autows=true,autosub='off'}},
	}},
	['wave3boss'] = { jobs = {
		['RDM'] = {	action={'mc buffall haste2; wait 1.0; mc buffall shell5; wait 1.0; hb buff me enthunder; hb buffjob tank refresh3,protect5,shell5; hb mincure 4; hb aoe on;',
					'hb buffjob GEO refresh3; dw3boss; gs c set weapons None; hb buffjob SAM refresh3,windstorm; hb as attack off; wait 1; hb as nolock on; hb f off;'}, food='Tropical Crepe'},
		['PLD'] = {	action={'hb as off; hb f off;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 1; gs c set treasuremode tag; hb minwaltz 3; gs c weapons DualCarn; sing pl w3boss; sing n on; sing p on; sing d on; hb debuff wind threnody II; sing debuff carnage elegy; gs c set autozergmode off;',
					'wait 1.5; sing ballad 1 GEO; sing ballad 1 RDM;',
					'wait 1.5; sing sirvente tank; sing ballad 1 tank',}, food='Grape Daifuku'},
		['SAM'] = {	action={'gs c set hybridmode normal; gs c set weapons Dojikiri; gs c autows Tachi: Jinpu; gs c set DefenseDownMode tag; gs c set weaponskillmode Enmity;'}, food='Rolan. Daifuku'},
		['GEO'] = {	action={'gmalaise; iacumen; gs c autoentrust fury; hb mincure 4; hb aoe on',
					'wait 0.7; hb buffjob BRD aurorastorm; hb buffjob tank aurorastorm;'}, food='Grape Daifuku'},
		['COR'] = {	action={'gs c set weapons DualLeaden; gs c autows leaden salute; roll roll1 chaos; roll roll2 wizard;'}, food='Rolan. Daifuku'},
		['ALL'] = {	commands = 'input /autotarget off; hb unignore_debuff all defense down,slow,addle,inhibit tp,plague,dia,bio', mc_settings = {autows=true,autosub='off'}},
	}},
	['eboss'] = { jobs = { 
		['SCH'] = {	sj={
			['RDM'] ={action={'gs c set elementalmode earth; hb cancelbuffjob GEO all; hb cancelbuff me all; hb buffjob GEO sandstorm2; hb buff me sandstorm2; schnuke; gs c set magicburstmode lock'}, food='Tropical Crepe',},
			['WHM'] ={action={'gs c set elementalmode earth; hb cancelbuffjob BLM all; hb cancelbuff me all; hb buffjob BLM sandstorm2; hb buff me sandstorm2; schnuke; gs c set magicburstmode lock'}, food='Tropical Crepe',}}},
		['GEO'] = {	action={'indiacumen; iacumen; gmalaise; gs c autoentrust none; hb buffjob tank haste; gs c set magicburstmode lock;'}, food='Tropical Crepe'},
		['COR'] = {	action={'roll roll1 evokers; roll roll2 wizard; hb buff me haste; hb mincuraga 3'}},
		['RUN'] = {	action={'gs c set autotankmode on; gs c set runeelement tellus; gs c set hybridmode Ongo; hb buffjob COR refresh; mc foff; mc on;'}},
		['BLM'] = {	action={'gs c set elementalmode earth; gs c set magicburstmode lock'}},
		['ALL'] = {	commands = 'gs c set autowsmode off; lua u maa; ai on;', mc_settings = {autows=false,autosc=true}},
	}},
	['fboss'] = { jobs = {
		['SCH'] = {	sj={
			['RDM'] ={action={'gs c set elementalmode earth; hb cancelbuffjob GEO all; hb cancelbuff me all; hb buffjob GEO hailstorm2; hb buff me hailstorm2; schnuke; gs c set magicburstmode lock'}, food='Tropical Crepe',},
			['WHM'] ={action={'gs c set elementalmode earth; hb cancelbuffjob BLM all; hb cancelbuff me all; hb buffjob BLM hailstorm2; hb buff me hailstorm2; schnuke; gs c set magicburstmode lock'}, food='Tropical Crepe',}}},
		['GEO'] = {	action={'indiacumen; iacumen; gmalaise; gs c autoentrust none; hb buffjob tank haste; gs c set magicburstmode lock;'}, food='Tropical Crepe'},
		['COR'] = {	action={'roll roll1 evokers; roll roll2 wizard; hb buff me haste; hb mincuraga 3'}},
		['RUN'] = {	action={'gs c set autotankmode on; gs c set runeelement gelus; gs c set hybridmode Ongo; hb buffjob COR refresh; mc foff; mc on;'}},
		['BLM'] = {	action={'gs c set elementalmode ice; gs c set magicburstmode lock'}},
		['ALL'] = {	commands = 'gs c set autowsmode off; lua u maa; ai on;', mc_settings = {autows=false,autosc=true}},
	}},
	['gboss'] = { jobs = {
		['SCH'] = {	sj={
			['RDM'] ={action={'gs c set elementalmode earth; hb cancelbuffjob GEO all; hb cancelbuff me all; hb buffjob GEO firestorm2; hb buff me firestorm2; schnuke; gs c set magicburstmode lock'}, food='Tropical Crepe',},
			['WHM'] ={action={'gs c set elementalmode earth; hb cancelbuffjob BLM all; hb cancelbuff me all; hb buffjob BLM firestorm2; hb buff me firestorm2; schnuke; gs c set magicburstmode lock'}, food='Tropical Crepe',}}},
		['GEO'] = {	action={'indiacumen; iacumen; gmalaise; gs c autoentrust focus; hb buffjob tank haste; gs c set autozergmode on; gs c set magicburstmode lock;'}, food='Tropical Crepe'},
		['COR'] = {	action={'roll roll1 warlock; roll roll2 wizard; hb buff me haste; hb mincuraga 3; hb ignore_debuff all curse;'}},
		['RUN'] = {	action={'gs c set autotankmode on; gs c set runeelement ignis; barblizzard; gs c set hybridmode Ongo; hb buffjob COR refresh; mc foff; mc on;'}},
		['BLM'] = {	action={'gs c set elementalmode fire; gs c set magicburstmode lock'}},
		['ALL'] = {	commands = 'gs c set autowsmode off; lua u maa; ai on; lua r mobtimer; wait 2; mobtimer start', mc_settings = {autows=false,autosc=true}},
	}},
	['sortiesc'] = { jobs = {
		['RUN'] = {	action={'gs c set weapons Naegling;'}},
		['WHM'] = {	action={'lua u maa; mc buffall haste; hb buff me regen4,auspice'}},
		['BLU'] = {	action={'lua u maa; hb as attack off'}},
		['WAR'] = {	action={'hb as attack off'}},
		['BRD'] = {	action={'gs c set weapons DualCarn; gs c set autosambamode off; sing pl mage; hb disable cure; gs c set autobuffmode off; sing p off; sing ballad 1 GEO; sing ballad 1 WHM'}},
		['GEO'] = {	action={'lua u maa; irefresh; ghaste'}},
		['COR'] = {	action={'roll melee; gs c set weapons DualWildfire; gs c set autosambamode off'}},
		['ALL'] = {	commands = 'gs c set autowsmode off', mc_settings = {autosc=true,autows=false}},
	}},
	['sortiemb'] = { jobs = {
		['RUN'] = {	action={'lua l maa'}},
		['WHM'] = {	action={'lua u maa; mc buffall haste; hb buff me regen4,auspice'}},
		['BLU'] = {	action={'lua u maa; hb as attack off'}},
		['WAR'] = {	action={'lua l maa; hb as attack off'}},
		['BRD'] = {	action={'gs c set weapons DualCarn; gs c set autosambamode off; sing pl mage; hb disable cure; gs c set autobuffmode off; sing p off; sing ballad 1 GEO; sing ballad 1 WHM'}},
		['GEO'] = {	action={'lua u maa; irefresh; ghaste'}},
		['COR'] = {	action={'roll melee; gs c set weapons DualWildfire; gs c set autosambamode off'}},
		['ALL'] = {	commands = 'gs c set autowsmode off', mc_settings = {autosc=true,autows=false}},
	}},
	['sortiecleave'] = { jobs = {
		['RUN'] = {	action={'lua u maa'}},
		['WHM'] = {	action={'lua u maa; mc buffall haste; hb buff me regen4,auspice'}},
		['BLU'] = {	action={'lua u maa; azuresets set magic; gs c set weapons Magic; hb as attack on'}},
		['WAR'] = {	action={'hb as attack on; gs c set weapons Naegling;'}},
		['BRD'] = {	action={'gs c set weapons DualCarn; sing pl mage; hb enable cure; gs c set autobuffmode auto'}},
		['GEO'] = {	action={'lua u maa; iacumen; gmalaise'}},
		['COR'] = {	action={'roll magic;'}},
		['ALL'] = {	commands = 'gs c set autowsmode on', mc_settings = {autosc=false,autows=true}},
	}},
	['sortieboss'] = { jobs = {
		['RUN'] = {	action={'lua u maa; gs c set weapons Lionheart'}},
		['WHM'] = {	action={'lua u maa; mc buffall haste; hb buff me regen4,auspice'}},
		['BLU'] = {	action={'lua u maa; azuresets set melee; gs c set weapons NaegThib; hb as attack on'}},
		['WAR'] = {	action={'hb as attack on; gs c set weapons Naegling;'}},
		['BRD'] = {	action={'gs c set weapons DualSavage; sing pl melee; hb enable cure; gs c set autobuffmode auto; sing p on; sing ballad 1 GEO; sing ballad 1 WHM'}},
		['GEO'] = {	action={'lua u maa; iattune; gfury; gs c autoentrust refresh'}},
		['COR'] = {	action={'roll melee; gs c set weapons DualSavage'}},
		['ALL'] = {	commands = 'gs c set autowsmode on', mc_settings = {autosc=false,autows=true}},
	}},
	['sortienormal'] = { jobs = {
		['RUN'] = {	action={'lua u maa; gs c set weapons Epeolatry'}},
		['WHM'] = {	action={'lua u maa; mc buffall haste; hb buff me regen4,auspice'}},
		['BLU'] = {	action={'lua u maa; azuresets set melee; gs c set weapons TizThib; hb as attack on'}},
		['WAR'] = {	action={'hb as attack on; gs c set weapons Naegling;'}},
		['BRD'] = {	action={'gs c set weapons DualSavage; sing pl melee; hb enable cure; gs c set autobuffmode auto; sing p on; sing ballad 1 GEO; sing ballad 1 WHM'}},
		['GEO'] = {	action={'lua r maa; iacumen; gmalaise; gs c autoentrust refresh'}},
		['COR'] = {	action={'roll melee; gs c set weapons DualWildfire'}},
		['ALL'] = {	commands = 'gs c set autowsmode on', mc_settings = {autosc=false,autows=true}},
	}},
	['shinryu'] = { jobs = {
		['WHM'] = {	action={'hb buff me barfira; hb buff me barparalyzra; hb buff me aquaveil; hb buff me auspice; hb buffjob MNK haste; hb debuff dia2; hb buffjob BRD haste;'}},
		['SCH'] = {	action={'gs c set elementalmode light; hb debuff dia2; hb buff me regen5; hb buff me aquaveil; hb buffjob BRD aurorastorm2; hb buffjob WHM aurorastorm2; hb buffjob THF haste;',
					'hb buffjob COR haste; schheal;'}},
		['BRD'] = {	action={'wait 2.5; sing pl shin; sing n on; sing p on; gs c set weapons DualCarn; sing ballad 1 WHM; sing ballad 1 SCH; sing ballad 1 GEO;'}},
		['MNK'] = {	action={'gs c set hybridmode DT'}},
		['THF'] = {	action={'gs c set treasuremode fulltime;'}},
		['GEO'] = {	action={'irefresh; gfury; gs c autoentrust frailty; hb debuff dia2;'}},
		['ALL'] = {	commands = 'lua r gazecheck; wait 3; gaze ag off; wait 1; gaze ap on;', mc_settings = {autows=true}},
	}},
	['lilith'] = { jobs = {
		['WHM'] = {	action={'hb disable erase; hb buff <me> boost-str,auspice,regen4; hb ignore_debuff all curse;'}},
		['GEO'] = {	action={'gs c autogeo frailty; gs c autoindi fury; gs c autoentrust refresh; gs c autonuke Absorb-TP; gs c set autonukemode on;'}},
		['BRD'] = {	action={'wait 2.5; sing pl lilmnk; sing n on; sing p on; sing debuffing off; gs c set treasuremode tag; gs c autonuke Absorb-TP; gs c set autonukemode on;'}},
		['MNK'] = {	action={'gs c set hybridmode DT'}},
		['THF'] = {	action={'gs c set treasuremode fulltime; gs c autonuke Absorb-TP; gs c set autonukemode on;'}},
		['COR'] = {	action={'roll roll1 sam; roll roll2 allies; gs c set treasuremode tag; gs c set idlemode refresh; gs c autonuke Absorb-TP; gs c set autonukemode on;'}},
		['ALL'] = {	commands = '', mc_settings = {autows=false}},
	}},
	['alex'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> barstonra,barpetra,auspice; hb buffjob THF haste; hb buffjob tank haste;'}},
		['PLD'] = {	action={'gs c autows Savage Blade; wait 3; lua r react'}},
		['BRD'] = {	action={'wait 2.5; sing pl alex; sing p off; sing debuffing off; gs c set weapons DualSavage; gs c autows Savage Blade;'}},
		['WAR'] = {	action={'gs c set weapons Naegling'}},
		['THF'] = {	action={'gs c set weapons Naegling; gs c set treasuremode fulltime'}},
		['GEO'] = {	action={'gs c autogeo fury; gs c autoindi refresh; gs c autoentrust haste; hb buffjob WAR haste;'}},
		['ALL'] = {	commands = '', mc_settings = {autows=true}},
	}},
	['cait'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> baraera,barsilencera,auspice; hb buffjob tank regen4;'}},
		['RUN'] = {	action={'gs c set runeelement tenebrae; gs c set weapons lionheart; gs c autows resolution'}},
		['BRD'] = {	action={'wait 2.5; sing pl cait; sing p on; sing debuffing off; gs c set weapons DualCarn'}},
		['SMN'] = {	action={'gs c set idlemode DT; gs c set autowardmode Ward_Full; hb enable cure; hb enable na'}},
		['THF'] = {	action={'gs c set treasuremode fulltime'}},
		['COR'] = {	action={'gs c set weapons DualSavage; gs c autows Savage Blade; roll melee'}},
		['ALL'] = {	commands = 'gaze ap on', mc_settings = {autows=true}},
	}},
	['ouryu'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> barstonra,barpetra,auspice,regen4; hb buffjob COR haste'}},
		['RUN'] = {	action={'gaze ap off; gs c set runeelement flabra; gs c set hybridmode DTLite;'}},
		['BRD'] = {	action={'wait 2.5; sing pl ouryu; hb debuff dia2; hb buffjob tank haste'}},
		['GEO'] = {	action={'gfrailty; ifury; gs c autoentrust attunement; hb buffjob SAM haste'}},
		['SAM'] = {	action={'gs c weapons Masamune'}},
		['COR'] = {	action={'gs c set weapons DualSavage; gs c autows Savage Blade; roll melee'}},
		['ALL'] = {	commands = 'gaze ap on', mc_settings = {autows=true}},
	}},
	['gige'] = { jobs = {
		['RDM'] = {	action={'hb f dist 6; hb f j WAR; hb as nolock; hb as j WAR; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Gigelorum\'s Matamata\";',
					'hb debuff slow2,paralyze2,addle2,gravity2,dia3,inundation; hb buffjob tank refresh3; hb buffjob MNK refresh3; hb buffjob WAR refresh3; hb mincure 4; mc buffall haste2;'}, food='Tropical Crepe'},
		['RUN'] = {	action={'hb buff me shell5; hb as off; hb f off;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 2.5; sing pl gige; sing n on; sing p on; sing sirvente tank; sing ballad 1 tank; sing ballad 2 RDM; gs c set weapons Carnwenhan'}, food='Maringna'},
		['MNK'] = {	action={'gs c set weaponskillmode Enmity'}, food='Om. Sandwich'},
		['WAR'] = {	action={'lua l dressup; gs c set weapons Loxotic; gs c set weaponskillmode Enmity; hb f dist 12; hb f j TANK'}, food='Grape Daifuku'},
		['COR'] = {	action={'gs c set weapons Naegling; roll melee;'}, food='Grape Daifuku'},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['aris'] = { jobs = {
		['WHM'] = {	action={'hb buff me auspice,aquaveil,barfira,baramnesra; gs c set castingmode SIRD; mc buffall haste; hb debuff dia2; hb as j WAR; hb as nolock; hb disable erase'}, food='Maringna'},
		['GEO'] = {	action={'gs c autogeo fury; gs c autoindi barrier; gs c autoentrust STR'}, food='Maringna'},
		['BRD'] = {	action={'wait 2.5; sing pl aris; sing n on; sing p on; sing ballad 2 whm; gs c set weapons Carnwenhan; sing debuff carnage elegy; sing aoe off; sing d on;'}, food='Om. Sandwich'},
		['SAM'] = {	action={'gs c set weaponskillmode Enmity; gs c set defensedownmode on;'}, food='Om. Sandwich'},
		['WAR'] = {	action={'lua l dressup; gs c set weapons Naegling; gs c set autotomahawkmode on;'}, food='Om. Sandwich'},
		['COR'] = {	action={'gs c set weapons Naegling; roll melee;'}, food='Om. Sandwich'},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['procne'] = { jobs = {
		['RDM'] = {	action={'hb f dist 6; hb f j WAR; hb as nolock; hb as j WAR; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Procne\'s Tulfaire\"; hb buffjob tank shell5;',
					'hb debuff slow2,paralyze2,addle2,gravity2,dia3,inundation; hb buffjob tank refresh3; hb buffjob WAR refresh3; hb mincure 4; mc buffall haste2;'}, food='Tropical Crepe'},
		['PLD'] = {	action={'hb as off; hb f off;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 2.5; sing pl procne; sing n on; sing p on; sing ballad 1 tank; sing wind 1 tank; sing sirvente tank; sing ballad 2 RDM; gs c set weapons Carnwenhan'}, food='Grape Daifuku'},
		['DRG'] = {	action={'gs c set weapons Trishula;'}, food='Grape Daifuku'},
		['WAR'] = {	action={'lua l dressup; gs c set weapons ShiningOne; gs c set weaponskillmode Enmity;'}, food='Grape Daifuku'},
		['COR'] = {	action={'gs c set weapons Fomalhaut; roll melee;'}, food='Grape Daifuku'},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['henwen'] = { jobs = {
		['RDM'] = {	action={'hb f dist 6; hb f j WAR; hb as nolock; hb as j WAR; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Henwen\'s Raaz\";',
					'hb debuff slow2,paralyze2,addle2,gravity2,dia3,inundation; hb buffjob tank refresh3; hb buffjob MNK refresh3; hb buffjob WAR refresh3; hb mincure 4; mc buffall haste2;'}, food='Tropical Crepe'},
		['PLD'] = {	action={'hb buff me shell5; hb as off; hb f off;'}, food='Om. Sandwich'},
		['BRD'] = {	action={'wait 2.5; sing pl gige; sing n on; sing p on; sing sirvente tank; sing ballad 1 tank; sing ballad 2 RDM; gs c set weapons Carnwenhan'}, food='Grape Daifuku'},
		['MNK'] = {	action={'gs c set weaponskillmode Enmity'}, food='Grape Daifuku'},
		['WAR'] = {	action={'lua l dressup; gs c set weapons Loxotic; gs c set weaponskillmode Enmity; hb f dist 12; hb f j TANK; hb as j MNK; gs c set autotomahawkmode on;'}, food='Grape Daifuku'},
		['COR'] = {	action={'gs c set weapons Naegling; roll melee;'}, food='Grape Daifuku'},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['marm'] = { jobs = {
		['BLM'] = {	action={'gs c set MagicBurstMode lock; gs c set elementalmode lightning;'}, food='Tropical Crepe'},
		['SCH'] = {	action={'gs c set MagicBurstMode lock; gs c set elementalmode lightning; schnuke; gs c set autosubmode off;'}, food='Tropical Crepe'},
		['GEO'] = {	action={'gs c set MagicBurstMode lock; gs c set elementalmode lightning; iacumen; gs c autogeo INT; gs c autoentrust fend;'}, food='Tropical Crepe'},
		['COR'] = {	action={'gs c set weapons fomalhaut; roll roll1 evokers; roll roll2 wizards;'}, food='Grape Daifuku'},
		['RDM'] = {	action={'hb buffjob BLM refresh3,haste2; hb buffjob SCH refresh3,haste2; hb buffjob GEO refresh3,haste2; hb buffjob tank refresh3,haste2,shell5,protect5; hb buffjob COR flurry2;',
					'hb debuff slow2,paralyze2,gravity2,bio3,inundation; hb as nolock on; hb as j tank; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Marmorkrebs\'s Cracklaw\"; hb mincure 4'},
					food='Tropical Crepe'},
		['RUN'] = {	action={'gs c set hybridmode MEVA; gs c set RuneElement Sulpor; gs c set autotankmode on; hb buff me barwater; hb f off; ai dd off; gs c set MaintainVorV on'}, food='Om. Sandwich'},
		['ALL'] = {	commands = 'hb f dist 2.7; autoitem on;', mc_settings = {autows=false,autosc=true,autosub='off'}},
	}},
	['rask'] = { jobs = {
		['BLM'] = {	action={'gs c set MagicBurstMode lock; gs c set elementalmode wind;'}, food='Tropical Crepe'},
		['SCH'] = {	action={'gs c set MagicBurstMode lock; gs c set elementalmode wind; schnuke; gs c set autosubmode off;'}, food='Tropical Crepe'},
		['GEO'] = {	action={'gs c set MagicBurstMode lock; gs c set elementalmode wind; iacumen; gmalaise; gs c autoentrust INT'}, food='Tropical Crepe'},
		['COR'] = {	action={'gs c set weapons fomalhaut; roll roll1 evokers; roll roll2 wizards;'}, food='Grape Daifuku'},
		['RDM'] = {	action={'hb buffjob BLM refresh3,haste2; hb buffjob SCH refresh3,haste2; hb buffjob GEO refresh3,haste2; hb buffjob tank refresh3,haste2,shell5,protect5; hb buffjob COR flurry2;',
					'hb debuff slow2,paralyze2,gravity2,bio3,inundation; hb as nolock on; hb as j tank; hb mldb gravity2,bind,paralyze2,slow2; hb moblist on; hb moblist add \"Raskovniche\'s Snapweed\";'},
					food='Tropical Crepe'},
		['RUN'] = {	action={'gs c set hybridmode MEVA; gs c set RuneElement Flabra; gs c set autotankmode on; hb buff me barstone; hb f off'}, food='Om. Sandwich'},
		['ALL'] = {	commands = 'hb f dist 2.7; autoitem on;', mc_settings = {autows=false,autosc=true,autosub='off'}},
	}},
	['mboze1'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> barstonra,auspice; hb mincuraga 3; hb debuff silence,slow,dia2,paralyze; buffjob WAR haste; hb buffjob tank haste; hb as j WAR'}},
		['RUN'] = {	action={'gs c set runeelement flabra;'}},
		['BRD'] = {	action={'wait 2.5; sing pl mboze; sing n off; sing p off; sing debuffing off;'}},
		['WAR'] = {	action={'gs c set hybridmode SubtleBlow; gs c set weapons Naegling; gs c autows Savage Blade'}},
		['BLU'] = {	action={'gs c set castingmode resistant; gs c set AutoBLUSpam on; gs c set weapons MACC; azuresets set mboze'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['mboze2'] = { jobs = {
		['RDM'] = {	action={'hb debuff silence,slow2,dia3,paralyze2; hb buffjob SAM haste2; hb buffjob tank haste2,refresh3;'}},
		['SAM'] = {	action={'gs c set hybridmode SubtleBlow;'}},
		['COR'] = {	action={'roll melee;'}},
		['BST'] = {	action={'gs c set JugMode FatsoFargann'}},
		['PLD'] = {	action={'gs c set autotankmode on'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['mboze3'] = { jobs = {
		['SCH'] = {	action={'hb buff <me> regen5; schheal'}},
		['DRK'] = {	action={'gs c set hybridmode SubtleBlow;'}},
		['GEO'] = {	action={'gs c autoindi refresh; gs c autogeo fury; gs c autoentrust haste; gs c autogeotar DRK'}},
		['SMN'] = {	action={'gs c set AutoBPMode on; gs c set AutoWardMode Ward_Offense; gs c set avatar cait sith;'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['ongo1'] = { jobs = {
		['RUN'] = {	action={'gs c set runeelement tellus;'}},
		['BLU'] = {	action={'hb enable cure; azuresets set solo'}},
		['RDM'] = {	action={'hb buffjob BLM refresh3,haste2; hb buffjob BLU refresh3; hb buffjob tank haste2,refresh3; hb moblist on; hb moblist add Ongo; hb mldb bio3,slow2,paralyze2,silence;'}},
		['BLM'] = {	action={'gs c set magicburstmode lock; lua r maa'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['ongo2'] = { jobs = {
		['SMN'] = {	action={'gs c set avatar diabolos; gs c set autobpmode on;'}},
		['COR'] = {	action={'roll roll1 evokers; roll roll2 pup'}},
		['BRD'] = {	action={'sing pl mage; hb buffjob tank mage\'s ballad iii,lightning carol'}},
		['PLD'] = {	action={'gs c set weapons Aegis'}},
		['DRK'] = {	action={'hb moblist on; hb moblist add Ongo; hb mldb poison2,bio2;'}},
		['WHM'] = {	action={'hb buffjob tank shell5,regen4; hb buff me barthundra;'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['ongo3'] = { jobs = {
		['PUP'] = {	action={'gs c set AutoManeuvers TankMEVA; gs c set petmode TankMEVA; gs c set weapons Midnights; autocontrol equipset mevatank'}},
		['GEO'] = {	action={'gs c autogeo malaise; gs c autoindi acumen; gs c autoentrust refresh'}},
		['SCH'] = {	action={'reraise; wait 10; schnuke'}}, -- fix reraise???
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['gog1'] = { jobs = {
		['SCH'] = {	action={'hb buffjob tank shell5,regen5; schheal'}},
		['SAM'] = {	action={'gs c set hybridmode SubtleBlow;'}},
		['BLU'] = {	action={'gs c set castingmode resistant; gs c set AutoBLUSpam on; gs c set weapons MACC; azuresets set mboze'}},
		['PLD'] = {	action={'gs c set autotankmode on'}},
		['SMN'] = {	action={'gs c set AutoBPMode on; gs c set AutoWardMode Ward_Offense; gs c set avatar cait sith;'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['kalungafarm'] = { jobs = {
		['RUN'] = {	action={'gs c set autotankmode on; gs c set runeelement unda; hb buff me barfire'}},
		['SAM'] = {	action={'gs c set hybridmode SubtleBlow'}},
		['BRD'] = {	action={'sing pl meleeacc; sing ballad 2 WHM; sing ballad 1 tank; sing fire 1 tank; sing ballad 1 GEO; sing p on; sing n on; hb buffjob tank fire carol,mage\'s ballad iii;'}},
		['GEO'] = {	action={'gs c autoindi barrier; gs c autogeo fury; gs c autoentrust refresh; gs c autoentrustee WHM; gs c autogeotar SAM;'}},
		['WHM'] = {	action={'hb buffjob WAR haste,regen4; hb buff me barfira,auspice; hb buffjob tank haste,shell5; hb debuff dia2,silence,paralyze; hb as j tank; hb as nolock on;'}},		
		['BST'] = {	action={'gs c set JugMode FatsoFargann'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['gog2'] = { jobs = {
		['DRK'] = {	action={'gs c set hybridmode SubtleBlow'}},
		['COR'] = {	action={'roll melee'}},
		['RDM'] = {	action={'hb buffjob DRK haste2,refesh3,protect5,shell5; hb debuff bio3,slow2,paralyze2,gravity2; hb as nolock on; hb as j DRK;'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off', mc_settings = {autows=true}},
	}},
	['ngai'] = { jobs = {
		['WHM'] = {	action={'hb disable erase; hb buff <me> barwatera,barsleepra,auspice; gs c set castingmode SIRD; hb debuff dia2; hb buffjob MNK haste; hb buffjob WAR haste'}},
		['MNK'] = {	action={'gs c set hybridmode Tank; gs c set weaponskillmode tank'}},
		['BRD'] = {	action={'wait 2.5; sing pl ngai; sing n on; sing p on; sing debuffing off; gs c set weapons Carnwenhan; sing ballad 2 WHM'}},
		['GEO'] = {	action={'gs c autoindi fury; gs c autogeo barrier; gs c autoentrust STR;'}},
		['COR'] = {	action={'gs c set weapons Naegling; roll melee'}},
		['WAR'] = {	action={'gs c set weapons Loxotic'}},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['xev'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> baraera; gs c set castingmode SIRD; hb debuff dia2; hb disable na; mc buffall haste'}},
		['DNC'] = {	action={'gs c set weapons Terpsichore;'}},
		['BRD'] = {	action={'wait 2.5; sing pl xev; sing n on; sing p on; gs c set weapons Aeneas; gaze ap on sing ballad 2 WHM'}},
		['GEO'] = {	action={'gs c autoindi attunement; gs c autogeo fury; gs c autoentrust STR;'}},
		['COR'] = {	action={'gs c set weapons Fomalhaut; roll melee'}},
		['WAR'] = {	action={'gs c set weapons ShiningOne;'}},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['kalunga'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> barfira; gs c set castingmode SIRD; hb debuff dia2; hb disable erase; hb buffjob tank haste,shell5; hb buffjob DRK haste; hb buffjob COR haste;'}},
		['RUN'] = {	action={'gs c set runeelement unda; gs c set autotankmode on; hb buff <me> barfire'}},
		['BRD'] = {	action={'wait 2.5; sing pl kalunga; sing n on; sing p on; sing sirvente tank; sing ballad 2 WHM'}},
		['GEO'] = {	action={'gs c autoindi barrier; gs c autogeo fury; gs c autoentrust refresh;'}},
		['COR'] = {	action={'gs c set weapons Naegling; roll melee'}},
		['DRK'] = {	action={'gs c set weapons Caladbolg; gs c set weaponskillmode Emnity'}},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['kalungav25'] = { jobs = {
		['PLD'] = {	action={'hb buffjob run protect5;'}},
		['RUN'] = {	action={'gs c set runeelement unda; gs c set autotankmode on; hb buff <me> barfire'}},
		['BRD'] = {	action={'wait 2.5; sing pl kalunga; sing n on; sing p on; sing sirvente RUN; sing ballad 1 RUN; sing fire 1 RUN; sing ballad 2 PLD; sing ballad 1 RDM'}},
		['RDM'] = {	action={'hb buffjob pld shell5,refresh3,haste2; hb buffjob drk shell5,haste2,refresh3; hb buffjob run shell5,refresh3,haste2; hb buffjob cor shell5,haste2; hb as nolock on; hb as j RUN; hb debuff bio3,paralyze2,slow2,blind2,poison2'}},
		['COR'] = {	action={'gs c set weapons Naegling; roll melee'}},
		['DRK'] = {	action={'gs c set weaponskillmode Emnity'}},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autows=true}},
	}},
	['mbozepre'] = { jobs = {
		['RDM'] = {	action={'dmain; hb as j WAR; hb as nolock on; hb buffjob WAR haste2,protect5,shell5; hb buffjob SMN refresh3; hb mincure 4;'}},
		['SMN'] = {	action={'gs c set AutoBPMode on; gs c set AutoWardMode Ward_Offense; gs c set avatar cait sith;'}},
		['GEO'] = {	action={'gs c autoindi refresh; gs c autogeo fury; gs c autoentrust VIT; gs c autogeotar WAR; gs c autoentrustee WAR'}},
		['SCH'] = {	action={'hb buffjob WAR regen5; schheal'}},
		['WAR'] = {	action={'gs c set weapons Naegling; gs c set hybridmode SubtleBlow'}},
		['ALL'] = {	commands = 'gaze ap off', mc_settings = {autows=true}},
	}},
	['mboze'] = { jobs = {
		['WHM'] = {	action={'hb buff <me> barstonra,boost-vit,auspice; gs c set castingmode SIRD; hb mincuraga 3; hb debuff silence,slow,dia2,paralyze; hb buffjob DRK haste; hb buffjob COR haste; hb buffjob BRD haste;'}},
		['BRD'] = {	action={'wait 2.5; sing pl mboze; sing n off; sing p off; sing debuffing off; sing debuff wind threnody 2; hb debuff wind threnody ii;'}},
		['COR'] = {	action={'roll melee; gs c set weapons Naegling;'}},
		['BST'] = {	action={'gs c set JugMode ScissorlegXerin'}},
		['BLU'] = {	action={'azuresets set mboze; gs c set castingmode resistant; gs c set AutoBLUSpam on; gs c set weapons MACC; hb debuff silent storm; hb as nolock on; hb as j DRK'}},
		['DRK'] = {	action={'gs c set weapons KajaChopper; gs c set hybridmode SubtleBlow; gs c autows tp 1750; lua l dressup'}},
		['ALL'] = {	commands = 'autoitem on; gaze ap off; gs c othertargetws Mboze', mc_settings = {autows=true}},
	}},
	['ongo'] = { jobs = {
		['BLM'] = {	action={'gs c set magicburstmode lock;'}},
		['BRD'] = {	action={'wait 2.5; sing pl ongo; sing n on; sing p on; sing sirvente 1 BRD; hb debuff earth threnody ii; hb as j tank; hb as nolock on; sing march 1 tank; sing earth 2 tank'}},
		['SCH'] = {	action={'hb buff me regen5; hb buffjob BLM sandstorm2; schheal'}},
		['GEO'] = {	action={'gs c autoindi acumen; gs c autogeo malaise; gs c autoentrust INT;'}},
		['RUN'] = {	action={'gs c set hybridmode Ongo; gs c set weapons Lycurgos; gs c set runeelement Tellus; gs c set autotankmode on;'}},
		['COR'] = {	action={'roll roll1 wizard; roll roll2 warlock; gs c set weapons Fomalhaut'}},
		['ALL'] = {	commands = 'autoitem on', mc_settings = {autosc=true,autows=true}},
	}},
	['arepre'] = { jobs = {
		['RUN'] = {	action={'gs c set runeelement ignis; hb buffjob WHM refresh; gs c set autotankmode on;'}},
		['WHM'] = {	action={'hb buff me barblizzara,auspice,barparalyzra,boost-str; hb debuff dia2,silence,slow,paralyze; hb as j tank; hb as nolock on;'}},
		['SMN'] = {	action={'gs c set AutoBPMode on; gs c set AutoWardMode Ward_Offense; gs c set avatar cait sith;'}},
		['GEO'] = {	action={'gs c autoentrust refresh; gfury; ihaste'}},
		['SAM'] = {	action={'gaze ap off; gs c weapons ShiningOne; gs c set weaponskillmode SubtleBlow; gs c set hybridmode SubtleBlow'}},
		['ALL'] = {	commands = 'gaze ap off;', mc_settings = {autows=true}},
	}},
	['arerng'] = { jobs = {
		['RUN'] = {	action={'gs c set runeelement ignis; hb buff <me> barblizzard,shell5; gs c set hybridmode MEVA: lua r react; gs c set autotankmode on;'}},
		['SCH'] = {	action={'hb disable erase; schheal; gs c set autoapmode on;'}},
		['BRD'] = {	action={'wait 2.5; sing pl arebati; sing n off; sing p on; sing sirvente tank; sing ice 1 tank; sing ballad 2 SCH; hb debuff horde lullaby ii,horde lullaby,foe lullaby ii,foe lullaby; hb debuff off;'}},
		['GEO'] = {	action={'gs c autoindi fury; gs c autogeo agi; gs c autoentrust attunement; gs c autoentrustee RNG'}},
		['RNG'] = {	action={'gs c set weapons Armageddon; gs c set maintainaftermath on; gs c set rnghelper on; wait 2; gs c autows Last Stand;'}},
		['COR'] = {	action={'roll melee; gs c set maintainaftermath on; gs c set weapons Armageddon; gs c set rnghelper on; wait 2; gs c autows Last Stand;'}},
		['ALL'] = {	commands = 'gaze ap on;', mc_settings = {autows=true,rangedmode=true}},
	}},
	['arewar'] = { jobs = {
		['PLD'] = {	action={'lua r react; lua l dressup'}},
		['RDM'] = {	action={'dmain; wait 4; mc buffall haste2; wait 1; mc buffall shell5; hb debuff addle2; hb as j WAR; hb as nolock on; hb buffjob PLD refresh3; hb buff <me> gain-mnd; hb buffjob WAR shell5,protect5; hb mincure 4;'}},
		['BRD'] = {	action={'wait 2.5; sing debuff nocturne; sing debuffing off; sing p on; gs c set weaponskillmode SubtleBlow; gs c autows tp 1850; gs c set weapons Aeneas; sing pl arewar; sing n off; sing ballad 1 RDM; sing ballad 1 PLD; sing prelude 1 COR'}},
		['BST'] = {	action={'gs c set JugMode SweetCaroline; gs c set weapons Agwu'}},
		['WAR'] = {	action={'gaze ap off; gs c set weapons ShiningOne; gs c set hybridmode SubtleBlow; gs c set weaponskillmode SubtleBlow;'}},
		['COR'] = {	action={'roll melee; gs c set weapons Fomalhaut; gs c autows Last Stand; gs c autows tp 1850; gs c set weaponskillmode SubtleBlow;'}},
		['ALL'] = {	commands = 'gs c othertargetws Arebati;', mc_settings = {autows=true}},
	}},
	['bumbapre'] = { jobs = {
		['RUN'] = {	action={'gs c set autotankmode on; gs c set runeelement sulpor'}},
		['SCH'] = {	action={'schheal; wait 25; schnuke; hb buffjob BLM thunderstorm2; hb buff me thunderstorm2'}},
		['BLM'] = {	action={'lua r maa'}},
		['BST'] = {	action={'gs c set jugmode generousarthur;'}},
		['SMN'] = {	action={'gs c set autowardmode ward_offense; gs c set avatar cait sith; gs c set autobpmode'}},
		['RDM'] = {	action={'mldb bio3,slow2,paralyze2,silence,addle2,blind2,poison2; hb moblist on; hb moblist add Bumba; hb buffjob tank refresh3,haste2,shell5,protect5; hb buffjob BLM refresh3; hb mincure 3;'}},
		['ALL'] = {	commands = 'gaze ap on;', mc_settings = {autows=true}},
	}},
	['bumba'] = { jobs = {
		['WAR'] = {	action={'gs c set weapons Naegling;'}},
		['WHM'] = {	action={'mc buffall haste; hb buff <me> barblizzara,boost-str,barparalyzra,auspice; hb disable na; gs c set castingmode SIRD; hb debuff dia2; hb as attack off; wait 0.5; hb as nolock; hb as j WAR'}},
		['DRG'] = {	action={'gs c set weapons Naegling; callwyvern; gs c set AutoBondMode off;'}},
		['BRD'] = {	action={'wait 2.5; sing pl bumba; sing n on; sing p on; gs c set weapons Naegling; gs c autows Savage Blade; sing ballad 2 WHM'}},
		['GEO'] = {	action={'gs c autoindi barrier; gs c autogeo fury; gs c autoentrust str;'}},
		['COR'] = {	action={'roll melee; gs c set weapons Naegling;'}},
		['ALL'] = {	commands = 'gaze ap on;', mc_settings = {autows=true}},
	}},

}

return job_data