job_change_data = {
	['ambu'] = {name='Ambuscade', char1 = 'blu/rdm', char2 = 'pld/run', char3 = 'rdm/sch', char4 = 'brd/dnc', char5 = 'war/sam', char6 = 'cor/nin',},
	['ody'] = {name='Odyssey Farm', char1 = 'run/pld', char2 = 'sam/war', char3 = 'cor/nin', char4 = 'brd/rdm', char5 = 'whm/sch', char6 = 'sam/war',},
	['alex'] = {name='Alexander', char1 = 'pld/run', char2 = 'thf/war', char3 = 'war/drg', char4 = 'brd/nin', char5 = 'geo/rdm', char6 = 'whm/sch',},
	['sortie'] = {name='Sortie Melee', char1 = 'run/drk', char2 = 'cor/nin', char3 = 'blu/drg', char4 = 'brd/dnc', char5 = 'war/drg', char6 = 'whm/sch',},
	['sortie2'] = {name='Sortie Mage', char1 = 'run/pld', char2 = 'blm/rdm', char3 = 'sch/rdm', char4 = 'sch/whm', char5 = 'geo/rdm', char6 = 'cor/whm',},
	['shinryu'] = {name='Shinryu', char1 = 'thf/war', char2 = 'mnk/war', char3 = 'sch/whm', char4 = 'brd/dnc', char5 = 'whm/sch', char6 = 'geo/rdm',},
	['ouryu'] = {name='Ouryu', char1 = 'run/drk', char2 = 'sam/war', char3 = 'cor/dnc', char4 = 'brd/whm', char5 = 'whm/sch', char6 = 'geo/rdm',},
	['cait'] = {name='Cait Sith', char1 = 'run/drk', char2 = 'thf/war', char3 = 'cor/nin', char4 = 'brd/dnc', char5 = 'whm/sch', char6 = 'smn/whm',},
	['dyna'] = {name='Dnyamis W3', char1 = 'pld/blu', char2 = 'sam/drg', char3 = 'cor/nin', char4 = 'brd/dnc', char5 = 'rdm/sch', char6 = 'geo/sch',},
	['dyna2'] = {name='Dnyamis W3 - Alternative', char1 = 'pld/blu', char2 = 'cor/nin', char3 = 'rdm/sch', char4 = 'brd/dnc', char5 = 'geo/sch', char6 = 'sam/drg',},
	['mboze1'] = {name='Mboze Farm #1', char1 = 'blu/rdm', char2 = 'mnk/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'run/rdm', char6 = 'whm/rdm',},
	['mboze2'] = {name='Mboze Farm #2', char1 = 'pld/rdm', char2 = 'sam/rdm', char3 = 'rdm/thf', char4 = 'cor/rdm', char5 = 'bst/rdm', char6 = 'pup/rdm',},
	['mboze3'] = {name='Mboze Farm #3', char1 = 'thf/rdm', char2 = 'nin/rdm', char3 = 'drk/rdm', char4 = 'sch/rdm', char5 = 'geo/rdm', char6 = 'smn/rdm',},
	['ongo1'] = {name='Ongo Farm #1', char1 = 'run/rdm', char2 = 'blm/rdm', char3 = 'blu/rdm', char4 = 'war/rdm', char5 = 'rdm/thf', char6 = 'nin/rdm',},
	['ongo2'] = {name='Ongo Farm #2', char1 = 'pld/rdm', char2 = 'cor/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/rdm', char6 = 'smn/rdm',},
	['ongo3'] = {name='Ongo Farm #3', char1 = 'thf/rdm', char2 = 'pup/rdm', char3 = 'sch/rdm', char4 = 'geo/rdm', char5 = 'bst/rdm', char6 = 'mnk/rdm',},
	['bumbapre'] = {name='Bumba Pre-fight', char1 = 'run/rdm', char2 = 'bst/rdm', char3 = 'sch/rdm', char4 = 'blm/rdm', char5 = 'rdm/thf', char6 = 'smn/rdm',},
	['bumba'] = {name='Bumba Main', char1 = 'war/rdm', char2 = 'cor/rdm', char3 = 'drg/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'geo/rdm',},
	['bumba1'] = {name='Bumba Farm #1', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'rng/rdm', char4 = 'cor/rdm', char5 = 'rdm/thf', char6 = 'thf/rdm',},
	['bumba2'] = {name='Bumba Farm #2', char1 = 'run/rdm', char2 = 'nin/rdm', char3 = 'sch/rdm', char4 = 'blm/rdm', char5 = 'dnc/thf', char6 = 'smn/rdm',},
	['bumba3'] = {name='Bumba Farm #3', char1 = 'blu/rdm', char2 = 'mnk/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'pup/rdm',},
	['arebatipre'] = {name='Arebati Pre-fight', char1 = 'run/rdm', char2 = 'sam/rdm', char3 = 'geo/rdm', char4 = 'smn/rdm', char5 = 'whm/thf', char6 = 'mnk/rdm',},
	['arebatiwar'] = {name='Arebati Main - Melee', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'war/rdm', char4 = 'brd/rdm', char5 = 'rdm/thf', char6 = 'cor/rdm',},
	['arebatirng'] = {name='Arebati Main - Ranged', char1 = 'run/rdm', char2 = 'rng/rdm', char3 = 'sch/rdm', char4 = 'brd/rdm', char5 = 'geo/thf', char6 = 'cor/rdm',},
	['kalunga'] = {name='Kalunga Main', char1 = 'run/rdm', char2 = 'cor/rdm', char3 = 'drk/rdm', char4 = 'brd/rdm', char5 = 'whm/thf', char6 = 'geo/rdm',},
	['kalunga1'] = {name='Kalunga Farm #1', char1 = 'pld/rdm', char2 = 'bst/rdm', char3 = 'drk/rdm', char4 = 'sch/rdm', char5 = 'brd/rdm', char6 = 'mnk/rdm',},
	['kalunga2'] = {name='Kalunga Farm #2', char1 = 'run/rdm', char2 = 'sam/rdm', char3 = 'blu/rdm', char4 = 'geo/rdm', char5 = 'rdm/thf', char6 = 'thf/rdm',},
	['kalunga3'] = {name='Kalunga Farm #3', char1 = 'war/rdm', char2 = 'pup/rdm', char3 = 'cor/rdm', char4 = 'blm/rdm', char5 = 'whm/rdm', char6 = 'nini/rdm',},
}

return job_data