return {
	[31] = {name = {'Spatial Displacement'}},
	[33] = {name = {'Swirling Vortex'}},
	[50] = {name = {'Ironbound Gate','Gate: The Pit'}},
	[51] = {name = {'Engraved Tablet'}},
	[61] = {name = {'Engraved Tablet'}},
	[67] = {name = {'Ornamental Door'}},
	[71] = {name = {'Gate: The Pit'}},
	[72] = {name = {'Gilded Doors'}},
	[70] = {name = {'Engraved Tablet'}},
	[111] = {name = {'Trail Markings'}},
	[112] = {name = {'Trail Markings'}},
	[126] = {name = {'Transcendental Radiance'}},
	[133] = {name = {'Diaphanous Device','Diaphanous Device #A','Diaphanous Device #B','Diaphanous Device #C','Diaphanous Device #D','Diaphanous Gadget','Diaphanous Gadget #A','Diaphanous Gadget #B','Diaphanous Gadget #C','Diaphanous Gadget #D','Diaphanous Gadget #E','Diaphanous Gadget #F','Diaphanous Gadget #G','Diaphanous Gadget #H','Diaphanous Bitzer #A','Diaphanous Bitzer #B','Diaphanous Bitzer #C','Diaphanous Bitzer #D','Diaphanous Bitzer'}},
    [137] = {name = {'Veridical Conflux'}},
    [139] = {name = {'Burning Circle'}},
    [144] = {name = {'Burning Circle'}},
	[146] = {name = {'Burning Circle'}},	
    [163] = {name = {'Mahogany Door'}},
    [165] = {name = {'Throne Room'}},
    [168] = {name = {'Shimmering Circle'}},
	[182] = {name = {'Veridical Conflux','Veridical Conflux #01','Veridical Conflux #02','Veridical Conflux #03','Veridical Conflux #04','Veridical Conflux #05','Veridical Conflux #06','Veridical Conflux #07','Veridical Conflux #08','Veridical Conflux #09','Veridical Conflux #10','Veridical Conflux #11','Veridical Conflux #12','Veridical Conflux #13','Veridical Conflux #14','Veridical Conflux #15'}},
	[201] = {name = {'Wind Protocrystal'}},
	[202] = {name = {'Lightning Protocrystal'}},
	[203] = {name = {'Ice Protocrystal'}},
	[206] = {name = {'Burning Circle'}},
	[207] = {name = {'Fire Protocrystal'}},
	[209] = {name = {'Earth Protocrystal'}},
	[211] = {name = {'Water Protocrystal'}},
	[255] = {name = {'Cavernous Maw','Transcendental Radiance'}},
	[256] = {name = {'Dangueubert'}},
	[257] = {name = {'Cunegonde','Krepol','Glowing Hearth'}},
	[261] = {name = {'???'}},
	[263] = {name = {'???'}},
	[265] = {name = {'???'}},
	[268] = {name = {'???'}},
	[269] = {name = {'???'}},
	[270] = {name = {'???'}},
	[272] = {name = {'???'}},
	[273] = {name = {'???'}},
	[274] = {name = {'Entwined Roots'}},
	[275] = {name = {'Diaphanous Device','Diaphanous Device #A','Diaphanous Device #B','Diaphanous Device #C','Diaphanous Device #D','Diaphanous Gadget','Diaphanous Gadget #A','Diaphanous Gadget #B','Diaphanous Gadget #C','Diaphanous Gadget #D','Diaphanous Gadget #E','Diaphanous Gadget #F','Diaphanous Gadget #G','Diaphanous Gadget #H','Diaphanous Bitzer #A','Diaphanous Bitzer #B','Diaphanous Bitzer #C','Diaphanous Bitzer #D','Diaphanous Bitzer'}},
	[279] = {name = {'Translocator #1','Translocator #2','Veridical Conflux #1','Veridical Conflux #2','Veridical Conflux #3','Veridical Conflux #4','Veridical Conflux #5','Veridical Conflux #6','Veridical Conflux #7','Veridical Conflux #8','Veridical Conflux #9','Veridical Conflux #10','Veridical Conflux #11','Otherworldly Vortex'}},
	[283] = {name = {'Dusky Forest','Reglert'}},
	[298] = {name = {'Translocator #1','Translocator #2','Veridical Conflux #1','Veridical Conflux #2','Veridical Conflux #3','Veridical Conflux #4','Veridical Conflux #5','Veridical Conflux #6','Veridical Conflux #7','Veridical Conflux #8','Veridical Conflux #9','Veridical Conflux #10','Veridical Conflux #11','Otherworldly Vortex'}},
}